In [2]:
## feature scaling

import numpy as np

salary = np.array([1000000, 2000000, 3000000, 4000000, 5000000, 6000000])
salary_inMil = salary / 1000000
salary_inMil

array([1., 2., 3., 4., 5., 6.])

In [3]:
# Sample dataset of e-commerce transactions
# Create a dictionary of multiple data items
# Displaying the dataset

import numpy as np
import pandas as pd

data = [
    {"ID": 1001, "Name": "Alice Smith",  "Email": "alice@example.com",        "Product": "Laptop",     "Quantity": 1,    "Price": 1200.00, "Purchase Date": "2024-09-15",   "Delivery Status": True},
    {"ID": 1002, "Name": "Bob Jones",    "Email": None,                       "Product": "Headphones", "Quantity": 2,    "Price": 150.00,  "Purchase Date": "2024-09-16",   "Delivery Status": True},
    {"ID": 1003, "Name": "Charlie John", "Email": "charlie#example.com",      "Product": "Smartphone", "Quantity": 1,    "Price": 800.00,  "Purchase Date": "16/09/2024",   "Delivery Status": True},
    {"ID": 1004, "Name": "David Lee",    "Email": "david.lee@example.com",    "Product": "Laptop",     "Quantity": 1,    "Price": 1200.00, "Purchase Date": "2024-09-17",   "Delivery Status": False},
    {"ID": 1005, "Name": "Eve Martinez", "Email": "eve.martinez@example.com", "Product": "Smartwatch", "Quantity": 3,    "Price": None,    "Purchase Date": "17th Sep 2024","Delivery Status": True},
    {"ID": 1006, "Name": "Frank Wright", "Email": None,                       "Product": "Tablet",     "Quantity": None, "Price": 600.00,  "Purchase Date": "2024-09-18",   "Delivery Status": False},
    {"ID": 1007, "Name": "Grace Lee",    "Email": "grace.lee@example.com",    "Product": "Laptop",     "Quantity": 1,    "Price": 1200.00, "Purchase Date": "2024-09-19",   "Delivery Status": True},
    {"ID": 1008, "Name": "Hank Brown",   "Email": "hank.brown@example.com",   "Product": "Monitor",    "Quantity": 2,    "Price": 300.00,  "Purchase Date": "09/19/2024",   "Delivery Status": True},
    {"ID": 1009, "Name": "Ivy Thompson", "Email": None,                       "Product": "Keyboard",   "Quantity": 2,    "Price": 100.00,  "Purchase Date": "2024/09/20",   "Delivery Status": False},
    {"ID": 1010, "Name": "Jack Davis",   "Email": "jack@example.com",         "Product": "Mouse",      "Quantity": 5,    "Price": 50.00,   "Purchase Date": "2024-09-21",   "Delivery Status": True},
    {"ID": 1011, "Name": "Alice Smith",  "Email": "alice@example.com",        "Product": "Laptop",     "Quantity": 1,    "Price": 1200.00, "Purchase Date": "2024-09-15",   "Delivery Status": True},  # Duplicate entry
    {"ID": 1012, "Name": "Kurt Evans",   "Email": "kurt.evans@example.com",   "Product": "Smartwatch", "Quantity": -1,   "Price": 200.00,  "Purchase Date": "2024-09-22",   "Delivery Status": True},  # Outlier quantity
    {"ID": 1013, "Name": "Liam Adams",   "Email": "liam.adams@example.com",   "Product": "Headphones", "Quantity": 2,    "Price": 150.00,  "Purchase Date": "2024-09-23",   "Delivery Status": False},
    {"ID": 1014, "Name": "Mia Clark",    "Email": "mia.clark@example.com",    "Product": None,         "Quantity": 1,    "Price": 0,       "Purchase Date": "2024-09-24",   "Delivery Status": True},  # Price anomaly
    {"ID": 1015, "Name": "Nina Turner",  "Email": None,                       "Product": "Tablet",     "Quantity": 1,    "Price": 600.00,  "Purchase Date": "24-09-2024",   "Delivery Status": True},
    {"ID": 1016, "Name": "Oscar Harris", "Email": "oscar.harris@example.com", "Product": "Laptop",     "Quantity": 2,    "Price": 1200.00, "Purchase Date": "2024-09-25",   "Delivery Status": True},
    {"ID": 1017, "Name": "Paul Young",   "Email": "paulyoung",                "Product": "Monitor",    "Quantity": 2,    "Price": 300.00,  "Purchase Date": "09/25/2024",   "Delivery Status": True},
    {"ID": 1018, "Name": "Quinn Lopez",  "Email": None,                       "Product": "Smartphone", "Quantity": 1,    "Price": 800.00,  "Purchase Date": "2024-09-26",   "Delivery Status": False},
    {"ID": 1019, "Name": "Rachel Scott", "Email": "rachel.scott@example.com", "Product": "Keyboard",   "Quantity": 2,    "Price": 100.00,  "Purchase Date": "2024-09-27",   "Delivery Status": True},
    {"ID": 1020, "Name": "Steve King",   "Email": "steve.king@example.com",   "Product": "Mouse",      "Quantity": None, "Price": 50.00,   "Purchase Date": "2024-09-28",   "Delivery Status": True},
]

# Displaying the dataset
import pandas as pd

# Convert the list of dictionaries to a DataFrame for easier visualization and manipulation
df = pd.DataFrame(data)
df

,ID,Name,Email,Product,Quantity,Price,Purchase Date,Delivery Status
0,1001,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
1,1002,Bob Jones,None,Headphones,2.0,150.0,2024-09-16,True
2,1003,Charlie John,charlie#example.com,Smartphone,1.0,800.0,16/09/2024,True
3,1004,David Lee,david.lee@example.com,Laptop,1.0,1200.0,2024-09-17,False
4,1005,Eve Martinez,eve.martinez@example.com,Smartwatch,3.0,NaN,17th Sep 2024,True
5,1006,Frank Wright,None,Tablet,NaN,600.0,2024-09-18,False
6,1007,Grace Lee,grace.lee@example.com,Laptop,1.0,1200.0,2024-09-19,True
7,1008,Hank Brown,hank.brown@example.com,Monitor,2.0,300.0,09/19/2024,True
8,1009,Ivy Thompson,None,Keyboard,2.0,100.0,2024/09/20,False
9,1010,Jack Davis,jack@example.com,Mouse,5.0,50.0,2024-09-21,True
10,1011,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
11,1012,Kurt Evans,kurt.evans@example.com,Smartwatch,-1.0,200.0,2024-09-22,True
12,1013,Liam Adams,liam.adams@example.com,Headphones,2.0,150.0,2024-09-23,False
13,1014,Mia Clark,mia.clark@example.com,None,1.0,0.0,2024-09-24,True
14,1015,Nina Turner,None,Tablet,1.0,600.0,24-09-2024,True
15,1016,Oscar Harris,oscar.harris@example.com,Laptop,2.0,1200.0,2024-09-25,True
16,1017,Paul Young,paulyoung,Monitor,2.0,300.0,09/25/2024,True
17,1018,Quinn Lopez,None,Smartphone,1.0,800.0,2024-09-26,False
18,1019,Rachel Scott,rachel.scott@example.com,Keyboard,2.0,100.0,2024-09-27,True
19,1020,Steve King,steve.king@example.com,Mouse,NaN,50.0,2024-09-28,True

## Handling Missing Values

# 1. Deletion - removal of missing values
# 1.1 - Listwise: rows where entry is missing
# 1.2 - Pairwise:

In [32]:
# data inspection

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               20 non-null     int64
 1   Name             20 non-null     object
 2   Email            15 non-null     object
 3   Product          19 non-null     object
 4   Quantity         20 non-null     float64
 5   Price            19 non-null     float64
 6   Purchase Date    20 non-null     object
 7   Delivery Status  20 non-null     bool
dtypes: bool(1), float64(2), int64(1), object(4)
memory usage: 1.2+ KB

In [33]:
# missing value check - using isna()

df.isna()

,ID,Name,Email,Product,Quantity,Price,Purchase Date,Delivery Status
0,False,False,False,False,False,False,False,False
1,False,False,True,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,True,False,False
5,False,False,True,False,False,False,False,False
6,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False
8,False,False,True,False,False,False,False,False
9,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False
13,False,False,False,True,False,False,False,False
14,False,False,True,False,False,False,False,False
15,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False
17,False,False,True,False,False,False,False,False
18,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False

In [34]:
# missing value check - using isnull()

df.isnull()
df.isnull().sum()

ID                 0
Name               0
Email              5
Product            1
Quantity           0
Price              1
Purchase Date      0
Delivery Status    0
dtype: int64

In [35]:
# missing value check - using duplicated()

df.duplicated()

df.duplicated().sum()

0

In [36]:
# listwise

df_listwise = df.dropna()
df_listwise.isna().sum()

df_listwise.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13 entries, 0 to 19
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               13 non-null     int64
 1   Name             13 non-null     object
 2   Email            13 non-null     object
 3   Product          13 non-null     object
 4   Quantity         13 non-null     float64
 5   Price            13 non-null     float64
 6   Purchase Date    13 non-null     object
 7   Delivery Status  13 non-null     bool
dtypes: bool(1), float64(2), int64(1), object(4)
memory usage: 845.0+ bytes

In [37]:
# pairwise deletion

df.isnull().sum()

df_pairwise = df.dropna(subset = 'Email')
df_pairwise.isnull().sum()

ID                 0
Name               0
Email              0
Product            1
Quantity           0
Price              1
Purchase Date      0
Delivery Status    0
dtype: int64

In [38]:
# pairwise deletion

df.isnull().sum()

df_pairwise = df.dropna(subset = ['Email', 'Product', 'Quantity'])
df_pairwise.isnull().sum()

df_pairwise.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14 entries, 0 to 19
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               14 non-null     int64
 1   Name             14 non-null     object
 2   Email            14 non-null     object
 3   Product          14 non-null     object
 4   Quantity         14 non-null     float64
 5   Price            13 non-null     float64
 6   Purchase Date    14 non-null     object
 7   Delivery Status  14 non-null     bool
dtypes: bool(1), float64(2), int64(1), object(4)
memory usage: 910.0+ bytes

## IMPUTATION

In [32]:
# imputation: using mean

df2 = df.copy()

df2.isnull().sum()

df2 = df2.dropna(subset = ['Product'])

mean_qnty = df2.Quantity.mean()
mean_qnty

# df2.Quantity = df2['Quantity'].fillna(mean_qnty)

mode_qnty = df['Quantity'].mode()[0]

df2

,ID,Name,Email,Product,Quantity,Price,Purchase Date,Delivery Status
0,1001,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
1,1002,Bob Jones,None,Headphones,2.0,150.0,2024-09-16,True
2,1003,Charlie John,charlie#example.com,Smartphone,1.0,800.0,16/09/2024,True
3,1004,David Lee,david.lee@example.com,Laptop,1.0,1200.0,2024-09-17,False
4,1005,Eve Martinez,eve.martinez@example.com,Smartwatch,3.0,NaN,17th Sep 2024,True
5,1006,Frank Wright,None,Tablet,NaN,600.0,2024-09-18,False
6,1007,Grace Lee,grace.lee@example.com,Laptop,1.0,1200.0,2024-09-19,True
7,1008,Hank Brown,hank.brown@example.com,Monitor,2.0,300.0,09/19/2024,True
8,1009,Ivy Thompson,None,Keyboard,2.0,100.0,2024/09/20,False
9,1010,Jack Davis,jack@example.com,Mouse,5.0,50.0,2024-09-21,True
10,1011,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
11,1012,Kurt Evans,kurt.evans@example.com,Smartwatch,1.0,200.0,2024-09-22,True
12,1013,Liam Adams,liam.adams@example.com,Headphones,2.0,150.0,2024-09-23,False
14,1015,Nina Turner,None,Tablet,1.0,600.0,24-09-2024,True
15,1016,Oscar Harris,oscar.harris@example.com,Laptop,2.0,1200.0,2024-09-25,True
16,1017,Paul Young,paulyoung,Monitor,2.0,300.0,09/25/2024,True
17,1018,Quinn Lopez,None,Smartphone,1.0,800.0,2024-09-26,False
18,1019,Rachel Scott,rachel.scott@example.com,Keyboard,2.0,100.0,2024-09-27,True
19,1020,Steve King,steve.king@example.com,Mouse,NaN,50.0,2024-09-28,True

In [33]:
# imputation: using mode

df2 = df.copy()

df2.isnull().sum()

mode_qnty = df2.Quantity.mode()[0]
mode_qnty

df2.Quantity = df2['Quantity'].fillna(mode_qnty)

df2.Quantity

0     1.0
1     2.0
2     1.0
3     1.0
4     3.0
5     1.0
6     1.0
7     2.0
8     2.0
9     5.0
10    1.0
11    1.0
12    2.0
13    1.0
14    1.0
15    2.0
16    2.0
17    1.0
18    2.0
19    1.0
Name: Quantity, dtype: float64

In [ ]:
# eg if mode more that 1 value

a = [1,2,3,4,4,4,5,6,7,7,7]

arr = series(a)

In [34]:
# mode for the product group

df.groupby('Product')['Quantity'].agg(lambda x: x.mode()[0])

Product
Headphones    2.0
Keyboard      2.0
Laptop        1.0
Monitor       2.0
Mouse         5.0
Smartphone    1.0
Smartwatch    1.0
Tablet        1.0
Name: Quantity, dtype: float64

In [35]:
# sum or total by product group

df.groupby('Product')['Quantity'].sum()

Product
Headphones    4.0
Keyboard      4.0
Laptop        6.0
Monitor       4.0
Mouse         5.0
Smartphone    2.0
Smartwatch    4.0
Tablet        1.0
Name: Quantity, dtype: float64

In [36]:
# num of appearance

df.groupby('Product')['Quantity'].count()

Product
Headphones    2
Keyboard      2
Laptop        5
Monitor       2
Mouse         1
Smartphone    2
Smartwatch    2
Tablet        1
Name: Quantity, dtype: int64

In [37]:
# to change -1 value for quantity to + value using abs

import math

df2.Quantity = abs(df2['Quantity'])
df2.Quantity

0     1.0
1     2.0
2     1.0
3     1.0
4     3.0
5     1.0
6     1.0
7     2.0
8     2.0
9     5.0
10    1.0
11    1.0
12    2.0
13    1.0
14    1.0
15    2.0
16    2.0
17    1.0
18    2.0
19    1.0
Name: Quantity, dtype: float64

In [38]:
df2.Quantity = (df2['Quantity']**2) ** 0.5
df2.Quantity

0     1.0
1     2.0
2     1.0
3     1.0
4     3.0
5     1.0
6     1.0
7     2.0
8     2.0
9     5.0
10    1.0
11    1.0
12    2.0
13    1.0
14    1.0
15    2.0
16    2.0
17    1.0
18    2.0
19    1.0
Name: Quantity, dtype: float64

In [41]:
df2 = df.copy()

df2['Email'] = df2['Email'].replace(['None'], None)

df2.loc[~df2['Email'].str.contains('@', na=False), 'Email'] = None

df2

,ID,Name,Email,Product,Quantity,Price,Purchase Date,Delivery Status
0,1001,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
1,1002,Bob Jones,None,Headphones,2.0,150.0,2024-09-16,True
2,1003,Charlie John,None,Smartphone,1.0,800.0,16/09/2024,True
3,1004,David Lee,david.lee@example.com,Laptop,1.0,1200.0,2024-09-17,False
4,1005,Eve Martinez,eve.martinez@example.com,Smartwatch,3.0,NaN,17th Sep 2024,True
5,1006,Frank Wright,None,Tablet,NaN,600.0,2024-09-18,False
6,1007,Grace Lee,grace.lee@example.com,Laptop,1.0,1200.0,2024-09-19,True
7,1008,Hank Brown,hank.brown@example.com,Monitor,2.0,300.0,09/19/2024,True
8,1009,Ivy Thompson,None,Keyboard,2.0,100.0,2024/09/20,False
9,1010,Jack Davis,jack@example.com,Mouse,5.0,50.0,2024-09-21,True
10,1011,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
11,1012,Kurt Evans,kurt.evans@example.com,Smartwatch,1.0,200.0,2024-09-22,True
12,1013,Liam Adams,liam.adams@example.com,Headphones,2.0,150.0,2024-09-23,False
13,1014,Mia Clark,mia.clark@example.com,None,1.0,0.0,2024-09-24,True
14,1015,Nina Turner,None,Tablet,1.0,600.0,24-09-2024,True
15,1016,Oscar Harris,oscar.harris@example.com,Laptop,2.0,1200.0,2024-09-25,True
16,1017,Paul Young,None,Monitor,2.0,300.0,09/25/2024,True
17,1018,Quinn Lopez,None,Smartphone,1.0,800.0,2024-09-26,False
18,1019,Rachel Scott,rachel.scott@example.com,Keyboard,2.0,100.0,2024-09-27,True
19,1020,Steve King,steve.king@example.com,Mouse,NaN,50.0,2024-09-28,True

In [43]:
df2['Generated Email'] = (
    df['Name']
    .str.lower()
    .str.strip()
    .str.replace(" ", ".") +
    "@example.com"
)

df2

,ID,Name,Email,Product,Quantity,Price,Purchase Date,Delivery Status,Generated Email
0,1001,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True,alice.smith@example.com
1,1002,Bob Jones,None,Headphones,2.0,150.0,2024-09-16,True,bob.jones@example.com
2,1003,Charlie John,None,Smartphone,1.0,800.0,16/09/2024,True,charlie.john@example.com
3,1004,David Lee,david.lee@example.com,Laptop,1.0,1200.0,2024-09-17,False,david.lee@example.com
4,1005,Eve Martinez,eve.martinez@example.com,Smartwatch,3.0,NaN,17th Sep 2024,True,eve.martinez@example.com
5,1006,Frank Wright,None,Tablet,NaN,600.0,2024-09-18,False,frank.wright@example.com
6,1007,Grace Lee,grace.lee@example.com,Laptop,1.0,1200.0,2024-09-19,True,grace.lee@example.com
7,1008,Hank Brown,hank.brown@example.com,Monitor,2.0,300.0,09/19/2024,True,hank.brown@example.com
8,1009,Ivy Thompson,None,Keyboard,2.0,100.0,2024/09/20,False,ivy.thompson@example.com
9,1010,Jack Davis,jack@example.com,Mouse,5.0,50.0,2024-09-21,True,jack.davis@example.com
10,1011,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True,alice.smith@example.com
11,1012,Kurt Evans,kurt.evans@example.com,Smartwatch,1.0,200.0,2024-09-22,True,kurt.evans@example.com
12,1013,Liam Adams,liam.adams@example.com,Headphones,2.0,150.0,2024-09-23,False,liam.adams@example.com
13,1014,Mia Clark,mia.clark@example.com,None,1.0,0.0,2024-09-24,True,mia.clark@example.com
14,1015,Nina Turner,None,Tablet,1.0,600.0,24-09-2024,True,nina.turner@example.com
15,1016,Oscar Harris,oscar.harris@example.com,Laptop,2.0,1200.0,2024-09-25,True,oscar.harris@example.com
16,1017,Paul Young,None,Monitor,2.0,300.0,09/25/2024,True,paul.young@example.com
17,1018,Quinn Lopez,None,Smartphone,1.0,800.0,2024-09-26,False,quinn.lopez@example.com
18,1019,Rachel Scott,rachel.scott@example.com,Keyboard,2.0,100.0,2024-09-27,True,rachel.scott@example.com
19,1020,Steve King,steve.king@example.com,Mouse,NaN,50.0,2024-09-28,True,steve.king@example.com

In [45]:
df2['Email'] = df2['Email'].fillna(df2['Generated Email'])
df2

,ID,Name,Email,Product,Quantity,Price,Purchase Date,Delivery Status,Generated Email
0,1001,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True,alice.smith@example.com
1,1002,Bob Jones,bob.jones@example.com,Headphones,2.0,150.0,2024-09-16,True,bob.jones@example.com
2,1003,Charlie John,charlie.john@example.com,Smartphone,1.0,800.0,16/09/2024,True,charlie.john@example.com
3,1004,David Lee,david.lee@example.com,Laptop,1.0,1200.0,2024-09-17,False,david.lee@example.com
4,1005,Eve Martinez,eve.martinez@example.com,Smartwatch,3.0,NaN,17th Sep 2024,True,eve.martinez@example.com
5,1006,Frank Wright,frank.wright@example.com,Tablet,NaN,600.0,2024-09-18,False,frank.wright@example.com
6,1007,Grace Lee,grace.lee@example.com,Laptop,1.0,1200.0,2024-09-19,True,grace.lee@example.com
7,1008,Hank Brown,hank.brown@example.com,Monitor,2.0,300.0,09/19/2024,True,hank.brown@example.com
8,1009,Ivy Thompson,ivy.thompson@example.com,Keyboard,2.0,100.0,2024/09/20,False,ivy.thompson@example.com
9,1010,Jack Davis,jack@example.com,Mouse,5.0,50.0,2024-09-21,True,jack.davis@example.com
10,1011,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True,alice.smith@example.com
11,1012,Kurt Evans,kurt.evans@example.com,Smartwatch,1.0,200.0,2024-09-22,True,kurt.evans@example.com
12,1013,Liam Adams,liam.adams@example.com,Headphones,2.0,150.0,2024-09-23,False,liam.adams@example.com
13,1014,Mia Clark,mia.clark@example.com,None,1.0,0.0,2024-09-24,True,mia.clark@example.com
14,1015,Nina Turner,nina.turner@example.com,Tablet,1.0,600.0,24-09-2024,True,nina.turner@example.com
15,1016,Oscar Harris,oscar.harris@example.com,Laptop,2.0,1200.0,2024-09-25,True,oscar.harris@example.com
16,1017,Paul Young,paul.young@example.com,Monitor,2.0,300.0,09/25/2024,True,paul.young@example.com
17,1018,Quinn Lopez,quinn.lopez@example.com,Smartphone,1.0,800.0,2024-09-26,False,quinn.lopez@example.com
18,1019,Rachel Scott,rachel.scott@example.com,Keyboard,2.0,100.0,2024-09-27,True,rachel.scott@example.com
19,1020,Steve King,steve.king@example.com,Mouse,NaN,50.0,2024-09-28,True,steve.king@example.com

In [52]:
df2['New_email'] = (df['Name']
                    .str.lower()
                    .str.strip()
                    .str.replace(" ", ".") 
                    + "@gmail.com")

df2

,ID,Name,Email,Product,Quantity,Price,Purchase Date,Delivery Status,New_email
0,1001,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True,alice.smith@gmail.com
1,1002,Bob Jones,bob.jones@example.com,Headphones,2.0,150.0,2024-09-16,True,bob.jones@gmail.com
2,1003,Charlie John,charlie.john@example.com,Smartphone,1.0,800.0,16/09/2024,True,charlie.john@gmail.com
3,1004,David Lee,david.lee@example.com,Laptop,1.0,1200.0,2024-09-17,False,david.lee@gmail.com
4,1005,Eve Martinez,eve.martinez@example.com,Smartwatch,3.0,NaN,17th Sep 2024,True,eve.martinez@gmail.com
5,1006,Frank Wright,frank.wright@example.com,Tablet,NaN,600.0,2024-09-18,False,frank.wright@gmail.com
6,1007,Grace Lee,grace.lee@example.com,Laptop,1.0,1200.0,2024-09-19,True,grace.lee@gmail.com
7,1008,Hank Brown,hank.brown@example.com,Monitor,2.0,300.0,09/19/2024,True,hank.brown@gmail.com
8,1009,Ivy Thompson,ivy.thompson@example.com,Keyboard,2.0,100.0,2024/09/20,False,ivy.thompson@gmail.com
9,1010,Jack Davis,jack@example.com,Mouse,5.0,50.0,2024-09-21,True,jack.davis@gmail.com
10,1011,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True,alice.smith@gmail.com
11,1012,Kurt Evans,kurt.evans@example.com,Smartwatch,1.0,200.0,2024-09-22,True,kurt.evans@gmail.com
12,1013,Liam Adams,liam.adams@example.com,Headphones,2.0,150.0,2024-09-23,False,liam.adams@gmail.com
13,1014,Mia Clark,mia.clark@example.com,None,1.0,0.0,2024-09-24,True,mia.clark@gmail.com
14,1015,Nina Turner,nina.turner@example.com,Tablet,1.0,600.0,24-09-2024,True,nina.turner@gmail.com
15,1016,Oscar Harris,oscar.harris@example.com,Laptop,2.0,1200.0,2024-09-25,True,oscar.harris@gmail.com
16,1017,Paul Young,paul.young@example.com,Monitor,2.0,300.0,09/25/2024,True,paul.young@gmail.com
17,1018,Quinn Lopez,quinn.lopez@example.com,Smartphone,1.0,800.0,2024-09-26,False,quinn.lopez@gmail.com
18,1019,Rachel Scott,rachel.scott@example.com,Keyboard,2.0,100.0,2024-09-27,True,rachel.scott@gmail.com
19,1020,Steve King,steve.king@example.com,Mouse,NaN,50.0,2024-09-28,True,steve.king@gmail.com

In [67]:
df2['New Email'] = (df2['Name']
.str.lower()
.str.strip()
.str.replace(" ",".")
+ "gmail.com")

df2

,ID,Name,Email,Product,Quantity,Price,Purchase Date,Delivery Status,New Email
0,1001,Alice Smith,alice.smithgmail.com,Laptop,1.0,1200.0,2024-09-15,True,alice.smithgmail.com
1,1002,Bob Jones,bob.jonesgmail.com,Headphones,2.0,150.0,2024-09-16,True,bob.jonesgmail.com
2,1003,Charlie John,charlie.johngmail.com,Smartphone,1.0,800.0,16/09/2024,True,charlie.johngmail.com
3,1004,David Lee,david.leegmail.com,Laptop,1.0,1200.0,2024-09-17,False,david.leegmail.com
4,1005,Eve Martinez,eve.martinezgmail.com,Smartwatch,3.0,NaN,17th Sep 2024,True,eve.martinezgmail.com
5,1006,Frank Wright,frank.wrightgmail.com,Tablet,NaN,600.0,2024-09-18,False,frank.wrightgmail.com
6,1007,Grace Lee,grace.leegmail.com,Laptop,1.0,1200.0,2024-09-19,True,grace.leegmail.com
7,1008,Hank Brown,hank.browngmail.com,Monitor,2.0,300.0,09/19/2024,True,hank.browngmail.com
8,1009,Ivy Thompson,ivy.thompsongmail.com,Keyboard,2.0,100.0,2024/09/20,False,ivy.thompsongmail.com
9,1010,Jack Davis,jack.davisgmail.com,Mouse,5.0,50.0,2024-09-21,True,jack.davisgmail.com
10,1011,Alice Smith,alice.smithgmail.com,Laptop,1.0,1200.0,2024-09-15,True,alice.smithgmail.com
11,1012,Kurt Evans,kurt.evansgmail.com,Smartwatch,1.0,200.0,2024-09-22,True,kurt.evansgmail.com
12,1013,Liam Adams,liam.adamsgmail.com,Headphones,2.0,150.0,2024-09-23,False,liam.adamsgmail.com
13,1014,Mia Clark,mia.clarkgmail.com,None,1.0,0.0,2024-09-24,True,mia.clarkgmail.com
14,1015,Nina Turner,nina.turnergmail.com,Tablet,1.0,600.0,24-09-2024,True,nina.turnergmail.com
15,1016,Oscar Harris,oscar.harrisgmail.com,Laptop,2.0,1200.0,2024-09-25,True,oscar.harrisgmail.com
16,1017,Paul Young,paul.younggmail.com,Monitor,2.0,300.0,09/25/2024,True,paul.younggmail.com
17,1018,Quinn Lopez,quinn.lopezgmail.com,Smartphone,1.0,800.0,2024-09-26,False,quinn.lopezgmail.com
18,1019,Rachel Scott,rachel.scottgmail.com,Keyboard,2.0,100.0,2024-09-27,True,rachel.scottgmail.com
19,1020,Steve King,steve.kinggmail.com,Mouse,NaN,50.0,2024-09-28,True,steve.kinggmail.com

In [71]:
df2 = df2.drop(columns = ['New Email'])
df2

KeyError: "['New Email'] not found in axis"