# Pandas
- python library
-fast, powerful, flexible and easy to use open source data "analysis" and "manipulation" tool
-provides series and dataframe object
-these object are use to store and manipulate structured data ( data in tabular form)

In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\vivo\.virtualenvs\.venv\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\vivo\.virtualenvs\.venv\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\vivo\.virtualenvs\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\vivo\.virtualenvs\.venv\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\Users\vivo\.virtualenvs\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

# core object
-series
-dataframe

In [5]:
marks = pd.Series([20,30,40])
type(marks)

print(marks)

0    20
1    30
2    40
dtype: int64

In [6]:
maths = pd.Series([20,30,40,], dtype = 'int8', name = 'math')
type(maths) 

print(maths)

0    20
1    30
2    40
Name: math, dtype: int8

In [7]:
english = pd.Series([20,30,40])
python = pd.Series([20,30,40])
science = pd.Series([20,30,40])

In [8]:
pd.concat([maths, english, python, science])

df = pd.concat([maths, english, python, science], axis=1)
df

   math   0   1   2
0    20  20  20  20
1    30  30  30  30
2    40  40  40  40

In [9]:
# dataframe from dictionary

data = {
    "Students": ["Nomie", "Idrees", "Radia"],
    "Maths": [85, 95, 90],
    "English": [75, 85, 80],
}

df = pd.DataFrame(data)

print(df)

  Students  Maths  English
0    Nomie     85       75
1   Idrees     95       85
2    Radia     90       80

In [10]:
data = [
    {'Name': 'Alice', 'Age': 25, 'City': 'New York'},
    {'Name': 'Bob', 'Age': 30, 'City': 'London'},
    {'Name': 'Charlie', 'Age': 35, 'City': 'Paris'}
]
 
df = pd.DataFrame(data)
print(df)
df

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris

In [11]:
data = [
    {'Name': 'Alice', 'Age': 25, 'City': 'New York'},
    {'Name': 'Bob', 'Age': 30, 'City': 'London'},
    {'Name': 'Charlie', 'Age': 35, 'City': 'Paris'}
]
 
df = pd.DataFrame(data)
print(df)
df

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris

NaN values
- not a number
- AKA missing values

Mini - activity:

1.Create a pd.Series with 5 temperature values and print it.
2.Create a pd.DataFrame with columns "city" and "temperature" for 3 cities.
3.Check the type() of each object you created.
4.add a name to your series and print it again.

In [12]:
data = {
    'City' : ['hanoi','tokyo','Kuala Lumpur'],
    'Temperature' : [30,4,34],
}
 
df = pd.DataFrame(data)   # onyl focus using in pd.DataFrame
display(df)

           City  Temperature
0         hanoi           30
1         tokyo            4
2  Kuala Lumpur           34

In [13]:
df = pd.DataFrame({
    "city": ["KL", "Penang", "Johor"],
    "temperature": [32, 30, 31]
})
print(df)

df

     city  temperature
0      KL           32
1  Penang           30
2   Johor           31

     city  temperature
0      KL           32
1  Penang           30
2   Johor           31

In [14]:
# Let's create a sample CSV file first, then read it
sample_data = """Name,Department,Salary,Experience
Alice,Engineering,75000,3
Bob,Marketing,65000,5
Charlie,Engineering,80000,7
Diana,HR,60000,2
Eve,Marketing,70000,4"""

with open("employee.csv", 'w') as f:
        f.write(sample_data)

# Read the CSV file
df = pd.read_csv("employee.csv")

print(df)

      Name   Department  Salary  Experience
0    Alice  Engineering   75000           3
1      Bob    Marketing   65000           5
2  Charlie  Engineering   80000           7
3    Diana           HR   60000           2
4      Eve    Marketing   70000           4

In [15]:
import pandas as pd

In [16]:
import os
print(os.getcwd())
print(os.path.exists("employees.csv"))

c:\Users\vivo\AIML-Nexperts-Batch5\AIML-Nexperts-Batch5\Practice\afif
False

In [17]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'Department': ['Engineering', 'Marketing', 'Engineering', 'HR', 'Marketing'],
    'Salary': [75000, 65000, 80000, 60000, 70000],
    'Experience': [3, 5, 2, 6, 4]
}

df = pd.DataFrame(data)

df

      Name   Department  Salary  Experience
0    Alice  Engineering   75000           3
1      Bob    Marketing   65000           5
2  Charlie  Engineering   80000           2
3    Diana           HR   60000           6
4      Eve    Marketing   70000           4

In [18]:
df[["Department", "Experience"]].iloc[-2:]

  Department  Experience
3         HR           6
4  Marketing           4

In [19]:
import pandas as pd

# Create a sample CSV file
sample_data = """Name,Department,Salary,Experience
Alice,Engineering,75000,3
Bob,Marketing,65000,5
Charlie,Engineering,80000,7
Diana,HR,60000,2
Eve,Marketing,70000,4"""

with open("employee.csv", "w") as f:
    f.write(sample_data)

# Read the CSV file
df = pd.read_csv("employee.csv")

print(df)

      Name   Department  Salary  Experience
0    Alice  Engineering   75000           3
1      Bob    Marketing   65000           5
2  Charlie  Engineering   80000           7
3    Diana           HR   60000           2
4      Eve    Marketing   70000           4

In [20]:
df[["Department", "Experience"]].iloc[-2:]

  Department  Experience
3         HR           2
4  Marketing           4

Adding and Modifying columns

In [21]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'Department': ['Math', 'Chemistry', 'Biology', 'Engineering', 'History'],
    'Salary': [50000, 60000, 55000, 62000, 58000],
    'Experience': [3, 5, 2, 4, 6]
})

df['Email'] = [
    'Alice@gmail.com',
    'Bob@gmail.com',
    'Charlie@gmail.com',
    'Diana@gmail.com',
    'Eve@gmail.com'
]

df.loc[2, 'Department'] = 'Physics'
df.Salary = df.Salary / 1000
df.Experience = df.Experience * 2

print(df)

df

      Name   Department  Salary  Experience              Email
0    Alice         Math    50.0           6    Alice@gmail.com
1      Bob    Chemistry    60.0          10      Bob@gmail.com
2  Charlie      Physics    55.0           4  Charlie@gmail.com
3    Diana  Engineering    62.0           8    Diana@gmail.com
4      Eve      History    58.0          12      Eve@gmail.com

      Name   Department  Salary  Experience              Email
0    Alice         Math    50.0           6    Alice@gmail.com
1      Bob    Chemistry    60.0          10      Bob@gmail.com
2  Charlie      Physics    55.0           4  Charlie@gmail.com
3    Diana  Engineering    62.0           8    Diana@gmail.com
4      Eve      History    58.0          12      Eve@gmail.com

Exercise:
- Please go to Kaggle
- Download this dataset: https://www.kaggle.com/datasets/juhibhojani/house-price
- perform the operations especially the EDA that we learnt about in today's class on it