In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("wc_2026.csv")

df.head()
df.tail()
df.sample(5)

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
99,NaN,Quarter-final,QF7,QF8,NRG Stadium,Houston,USA,2026-07-11,TBD,NaN,NaN,NaN,NaN,NaN,NaN
9,B,Group Stage,Canada,Qatar,BC Place,Vancouver,Canada,2026-06-19,18:00 ET,CONCACAF,30.0,Jesse Marsch,AFC,35.0,Marquez Lopez
74,NaN,Round of 32,1C,2D,NRG Stadium,Houston,USA,2026-06-29,TBD,NaN,NaN,NaN,NaN,NaN,NaN
34,F,Group Stage,Japan,Sweden,AT&T Stadium,Arlington,USA,2026-06-26,15:00 ET,AFC,18.0,Hajime Moriyasu,UEFA,39.0,Jon Dahl Tomasson
90,NaN,Round of 16,R32 W5,R32 W6,Rose Bowl,Pasadena,USA,2026-07-05,TBD,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df.shape # (104, 15)
df.size # 1560

df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   group                72 non-null     object
 1   stage                104 non-null    object
 2   team1                104 non-null    object
 3   team2                104 non-null    object
 4   venue                104 non-null    object
 5   city                 104 non-null    object
 6   country              104 non-null    object
 7   date                 104 non-null    object
 8   kickoff_et           104 non-null    object
 9   team1_confederation  72 non-null     object
 10  team1_fifa_rank      72 non-null     float64
 11  team1_coach          72 non-null     object
 12  team2_confederation  72 non-null     object
 13  team2_fifa_rank      72 non-null     float64
 14  team2_coach          72 non-null     object
dtypes: float64(2), object(13)
memory usage: 12.3+ KB

       team1_fifa_rank  team2_fifa_rank
count        72.000000        72.000000
mean         30.208333        37.916667
std          24.521297        23.836739
min           1.000000         1.000000
25%           9.750000        17.750000
50%          24.000000        35.500000
75%          44.000000        57.750000
max          95.000000        95.000000

In [ ]:
## Filtering
# - filter rows & cols
# - using boolean indexing
# - keeps only the rows that we need
# - df[condition] or df[mask]

In [16]:
df.head()

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
0,A,Group Stage,Mexico,South Africa,Estadio Azteca,Mexico City,Mexico,2026-06-11,20:00 ET,CONCACAF,15.0,Javier Aguirre,CAF,60.0,Hugo Broos
1,A,Group Stage,South Korea,Czechia,Estadio Akron,Guadalajara,Mexico,2026-06-11,22:00 ET,AFC,25.0,Hong Myung-bo,UEFA,41.0,Ivan Hasek
2,A,Group Stage,South Korea,Mexico,Estadio Akron,Guadalajara,Mexico,2026-06-18,21:00 ET,AFC,25.0,Hong Myung-bo,CONCACAF,15.0,Javier Aguirre
3,A,Group Stage,Czechia,South Africa,Estadio Akron,Guadalajara,Mexico,2026-06-18,18:00 ET,UEFA,41.0,Ivan Hasek,CAF,60.0,Hugo Broos
4,A,Group Stage,Czechia,Mexico,Estadio Azteca,Mexico City,Mexico,2026-06-24,21:00 ET,UEFA,41.0,Ivan Hasek,CONCACAF,15.0,Javier Aguirre

In [23]:
## to show the matches played in Canada

mask = df["country"] == "Canada"
df[mask]

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
6,B,Group Stage,Canada,Bosnia and Herzegovina,BMO Field,Toronto,Canada,2026-06-12,15:00 ET,CONCACAF,30.0,Jesse Marsch,UEFA,52.0,Sergej Barbarez
8,B,Group Stage,Switzerland,Bosnia and Herzegovina,BC Place,Vancouver,Canada,2026-06-18,15:00 ET,UEFA,19.0,Murat Yakin,UEFA,52.0,Sergej Barbarez
9,B,Group Stage,Canada,Qatar,BC Place,Vancouver,Canada,2026-06-19,18:00 ET,CONCACAF,30.0,Jesse Marsch,AFC,35.0,Marquez Lopez
10,B,Group Stage,Switzerland,Canada,BC Place,Vancouver,Canada,2026-06-24,18:00 ET,UEFA,19.0,Murat Yakin,CONCACAF,30.0,Jesse Marsch
11,B,Group Stage,Bosnia and Herzegovina,Qatar,BMO Field,Toronto,Canada,2026-06-24,18:00 ET,UEFA,52.0,Sergej Barbarez,AFC,35.0,Marquez Lopez
67,L,Group Stage,Ghana,Panama,BMO Field,Toronto,Canada,2026-06-17,18:00 ET,CAF,65.0,Otto Addo,CONCACAF,53.0,Thomas Christiansen
69,L,Group Stage,Croatia,Panama,BMO Field,Toronto,Canada,2026-06-23,21:00 ET,UEFA,11.0,Zlatko Dalić,CONCACAF,53.0,Thomas Christiansen
83,NaN,Round of 32,1L,2K,BC Place,Vancouver,Canada,2026-07-03,TBD,NaN,NaN,NaN,NaN,NaN,NaN
84,NaN,Round of 32,Best 3rd #1,Best 3rd #2,BMO Field,Toronto,Canada,2026-07-03,TBD,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
df[df['country'] == 'Canada']

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
6,B,Group Stage,Canada,Bosnia and Herzegovina,BMO Field,Toronto,Canada,2026-06-12,15:00 ET,CONCACAF,30.0,Jesse Marsch,UEFA,52.0,Sergej Barbarez
8,B,Group Stage,Switzerland,Bosnia and Herzegovina,BC Place,Vancouver,Canada,2026-06-18,15:00 ET,UEFA,19.0,Murat Yakin,UEFA,52.0,Sergej Barbarez
9,B,Group Stage,Canada,Qatar,BC Place,Vancouver,Canada,2026-06-19,18:00 ET,CONCACAF,30.0,Jesse Marsch,AFC,35.0,Marquez Lopez
10,B,Group Stage,Switzerland,Canada,BC Place,Vancouver,Canada,2026-06-24,18:00 ET,UEFA,19.0,Murat Yakin,CONCACAF,30.0,Jesse Marsch
11,B,Group Stage,Bosnia and Herzegovina,Qatar,BMO Field,Toronto,Canada,2026-06-24,18:00 ET,UEFA,52.0,Sergej Barbarez,AFC,35.0,Marquez Lopez
67,L,Group Stage,Ghana,Panama,BMO Field,Toronto,Canada,2026-06-17,18:00 ET,CAF,65.0,Otto Addo,CONCACAF,53.0,Thomas Christiansen
69,L,Group Stage,Croatia,Panama,BMO Field,Toronto,Canada,2026-06-23,21:00 ET,UEFA,11.0,Zlatko Dalić,CONCACAF,53.0,Thomas Christiansen
83,NaN,Round of 32,1L,2K,BC Place,Vancouver,Canada,2026-07-03,TBD,NaN,NaN,NaN,NaN,NaN,NaN
84,NaN,Round of 32,Best 3rd #1,Best 3rd #2,BMO Field,Toronto,Canada,2026-07-03,TBD,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
## exercise 2: data for the matches team1_fifa rank was <=10

mask = df["team1_fifa_rank"] <=10

df[mask]

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
12,C,Group Stage,Brazil,Morocco,MetLife Stadium,East Rutherford,USA,2026-06-13,18:00 ET,CONMEBOL,6.0,Dorival Júnior,CAF,8.0,Walid Regragui
14,C,Group Stage,Brazil,Scotland,MetLife Stadium,East Rutherford,USA,2026-06-19,21:00 ET,CONMEBOL,6.0,Dorival Júnior,UEFA,47.0,Steve Clarke
15,C,Group Stage,Morocco,Haiti,MetLife Stadium,East Rutherford,USA,2026-06-19,21:00 ET,CAF,8.0,Walid Regragui,CONCACAF,83.0,Marc Collat
17,C,Group Stage,Morocco,Haiti,Gillette Stadium,Foxborough,USA,2026-06-24,21:00 ET,CAF,8.0,Walid Regragui,CONCACAF,83.0,Marc Collat
24,E,Group Stage,Germany,Curaçao,NRG Stadium,Houston,USA,2026-06-14,13:00 ET,UEFA,10.0,Julian Nagelsmann,CONCACAF,81.0,Dick Advocaat
26,E,Group Stage,Germany,Ivory Coast,NRG Stadium,Houston,USA,2026-06-20,19:00 ET,UEFA,10.0,Julian Nagelsmann,CAF,33.0,Emerse Faé
30,F,Group Stage,Netherlands,Japan,AT&T Stadium,Arlington,USA,2026-06-14,16:00 ET,UEFA,7.0,Ronald Koeman,AFC,18.0,Hajime Moriyasu
32,F,Group Stage,Netherlands,Sweden,NRG Stadium,Houston,USA,2026-06-20,19:00 ET,UEFA,7.0,Ronald Koeman,UEFA,39.0,Jon Dahl Tomasson
36,G,Group Stage,Belgium,Egypt,Lumen Field,Seattle,USA,2026-06-15,15:00 ET,UEFA,9.0,Domenico Tedesco,CAF,29.0,Hossam El-Badry
38,G,Group Stage,Belgium,Iran,SoFi Stadium,Inglewood,USA,2026-06-21,18:00 ET,UEFA,9.0,Domenico Tedesco,AFC,21.0,Amir Ghalenoei
42,H,Group Stage,Spain,Cape Verde,Mercedes-Benz Stadium,Atlanta,USA,2026-06-15,12:00 ET,UEFA,2.0,Luis de la Fuente,CAF,70.0,Pedro Brito
44,H,Group Stage,Spain,Saudi Arabia,Estadio Akron,Guadalajara,Mexico,2026-06-21,21:00 ET,UEFA,2.0,Luis de la Fuente,AFC,57.0,Roberto Mancini
48,I,Group Stage,France,Senegal,MetLife Stadium,East Rutherford,USA,2026-06-16,15:00 ET,UEFA,1.0,Didier Deschamps,CAF,14.0,Aliou Cissé
50,I,Group Stage,France,Iraq,Lincoln Financial Field,Philadelphia,USA,2026-06-22,17:00 ET,UEFA,1.0,Didier Deschamps,AFC,61.0,Graham Arnold
54,J,Group Stage,Argentina,Algeria,Arrowhead Stadium,Kansas City,USA,2026-06-16,21:00 ET,CONMEBOL,3.0,Lionel Scaloni,CAF,36.0,Vladimir Petkovic
56,J,Group Stage,Argentina,Austria,AT&T Stadium,Arlington,USA,2026-06-22,13:00 ET,CONMEBOL,3.0,Lionel Scaloni,UEFA,23.0,Ralf Rangnick
60,K,Group Stage,Portugal,DR Congo,NRG Stadium,Houston,USA,2026-06-17,13:00 ET,UEFA,5.0,Roberto Martínez,CAF,51.0,Sébastien Desabre
62,K,Group Stage,Portugal,Uzbekistan,Arrowhead Stadium,Kansas City,USA,2026-06-23,13:00 ET,UEFA,5.0,Roberto Martínez,AFC,62.0,Srecko Katanec
66,L,Group Stage,England,Croatia,AT&T Stadium,Arlington,USA,2026-06-17,15:00 ET,UEFA,4.0,Thomas Tuchel,UEFA,11.0,Zlatko Dalić
68,L,Group Stage,England,Ghana,Gillette Stadium,Foxborough,USA,2026-06-23,19:00 ET,UEFA,4.0,Thomas Tuchel,CAF,65.0,Otto Addo

In [ ]:
## exercise 2: data for the matches team1_fifa rank was <=10

df[df["team1_fifa_rank"] <=10]

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
12,C,Group Stage,Brazil,Morocco,MetLife Stadium,East Rutherford,USA,2026-06-13,18:00 ET,CONMEBOL,6.0,Dorival Júnior,CAF,8.0,Walid Regragui
14,C,Group Stage,Brazil,Scotland,MetLife Stadium,East Rutherford,USA,2026-06-19,21:00 ET,CONMEBOL,6.0,Dorival Júnior,UEFA,47.0,Steve Clarke
15,C,Group Stage,Morocco,Haiti,MetLife Stadium,East Rutherford,USA,2026-06-19,21:00 ET,CAF,8.0,Walid Regragui,CONCACAF,83.0,Marc Collat
17,C,Group Stage,Morocco,Haiti,Gillette Stadium,Foxborough,USA,2026-06-24,21:00 ET,CAF,8.0,Walid Regragui,CONCACAF,83.0,Marc Collat
24,E,Group Stage,Germany,Curaçao,NRG Stadium,Houston,USA,2026-06-14,13:00 ET,UEFA,10.0,Julian Nagelsmann,CONCACAF,81.0,Dick Advocaat
26,E,Group Stage,Germany,Ivory Coast,NRG Stadium,Houston,USA,2026-06-20,19:00 ET,UEFA,10.0,Julian Nagelsmann,CAF,33.0,Emerse Faé
30,F,Group Stage,Netherlands,Japan,AT&T Stadium,Arlington,USA,2026-06-14,16:00 ET,UEFA,7.0,Ronald Koeman,AFC,18.0,Hajime Moriyasu
32,F,Group Stage,Netherlands,Sweden,NRG Stadium,Houston,USA,2026-06-20,19:00 ET,UEFA,7.0,Ronald Koeman,UEFA,39.0,Jon Dahl Tomasson
36,G,Group Stage,Belgium,Egypt,Lumen Field,Seattle,USA,2026-06-15,15:00 ET,UEFA,9.0,Domenico Tedesco,CAF,29.0,Hossam El-Badry
38,G,Group Stage,Belgium,Iran,SoFi Stadium,Inglewood,USA,2026-06-21,18:00 ET,UEFA,9.0,Domenico Tedesco,AFC,21.0,Amir Ghalenoei
42,H,Group Stage,Spain,Cape Verde,Mercedes-Benz Stadium,Atlanta,USA,2026-06-15,12:00 ET,UEFA,2.0,Luis de la Fuente,CAF,70.0,Pedro Brito
44,H,Group Stage,Spain,Saudi Arabia,Estadio Akron,Guadalajara,Mexico,2026-06-21,21:00 ET,UEFA,2.0,Luis de la Fuente,AFC,57.0,Roberto Mancini
48,I,Group Stage,France,Senegal,MetLife Stadium,East Rutherford,USA,2026-06-16,15:00 ET,UEFA,1.0,Didier Deschamps,CAF,14.0,Aliou Cissé
50,I,Group Stage,France,Iraq,Lincoln Financial Field,Philadelphia,USA,2026-06-22,17:00 ET,UEFA,1.0,Didier Deschamps,AFC,61.0,Graham Arnold
54,J,Group Stage,Argentina,Algeria,Arrowhead Stadium,Kansas City,USA,2026-06-16,21:00 ET,CONMEBOL,3.0,Lionel Scaloni,CAF,36.0,Vladimir Petkovic
56,J,Group Stage,Argentina,Austria,AT&T Stadium,Arlington,USA,2026-06-22,13:00 ET,CONMEBOL,3.0,Lionel Scaloni,UEFA,23.0,Ralf Rangnick
60,K,Group Stage,Portugal,DR Congo,NRG Stadium,Houston,USA,2026-06-17,13:00 ET,UEFA,5.0,Roberto Martínez,CAF,51.0,Sébastien Desabre
62,K,Group Stage,Portugal,Uzbekistan,Arrowhead Stadium,Kansas City,USA,2026-06-23,13:00 ET,UEFA,5.0,Roberto Martínez,AFC,62.0,Srecko Katanec
66,L,Group Stage,England,Croatia,AT&T Stadium,Arlington,USA,2026-06-17,15:00 ET,UEFA,4.0,Thomas Tuchel,UEFA,11.0,Zlatko Dalić
68,L,Group Stage,England,Ghana,Gillette Stadium,Foxborough,USA,2026-06-23,19:00 ET,UEFA,4.0,Thomas Tuchel,CAF,65.0,Otto Addo

In [ ]:
## exercise 3: data for the matches both teams rank was <10

mask = (df["team1_fifa_rank"] <10) & (df["team2_fifa_rank"] <10)

df[(df["team1_fifa_rank"] <10) & (df["team2_fifa_rank"] <10)]

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
12,C,Group Stage,Brazil,Morocco,MetLife Stadium,East Rutherford,USA,2026-06-13,18:00 ET,CONMEBOL,6.0,Dorival Júnior,CAF,8.0,Walid Regragui

In [ ]:
## exercise 3: data for the matches both teams rank was <10

df[(df["team1_fifa_rank"] <10) & (df["team2_fifa_rank"] <10)]

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
12,C,Group Stage,Brazil,Morocco,MetLife Stadium,East Rutherford,USA,2026-06-13,18:00 ET,CONMEBOL,6.0,Dorival Júnior,CAF,8.0,Walid Regragui

In [33]:
## exercise 4: Find all matches where Mexico is playing, specifically as team1 AND the venue is "Estadio Azteca"

mask = (df["team1"] == "Mexico") & (df["venue"] == "Estadio Azteca")
df[mask]

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
0,A,Group Stage,Mexico,South Africa,Estadio Azteca,Mexico City,Mexico,2026-06-11,20:00 ET,CONCACAF,15.0,Javier Aguirre,CAF,60.0,Hugo Broos

In [34]:
## exercise 4: Find all matches where Mexico is playing, specifically as team1 AND the venue is "Estadio Azteca"

df[(df["team1"] == "Mexico") & (df["venue"] == "Estadio Azteca")]

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
0,A,Group Stage,Mexico,South Africa,Estadio Azteca,Mexico City,Mexico,2026-06-11,20:00 ET,CONCACAF,15.0,Javier Aguirre,CAF,60.0,Hugo Broos

In [39]:
## exercise 5: Find all matches played in either "Toronto" or "Vancouver"

mask = (df["city"] == "Toronto") | (df["city"] == "Vancouver")
df[mask]

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
6,B,Group Stage,Canada,Bosnia and Herzegovina,BMO Field,Toronto,Canada,2026-06-12,15:00 ET,CONCACAF,30.0,Jesse Marsch,UEFA,52.0,Sergej Barbarez
8,B,Group Stage,Switzerland,Bosnia and Herzegovina,BC Place,Vancouver,Canada,2026-06-18,15:00 ET,UEFA,19.0,Murat Yakin,UEFA,52.0,Sergej Barbarez
9,B,Group Stage,Canada,Qatar,BC Place,Vancouver,Canada,2026-06-19,18:00 ET,CONCACAF,30.0,Jesse Marsch,AFC,35.0,Marquez Lopez
10,B,Group Stage,Switzerland,Canada,BC Place,Vancouver,Canada,2026-06-24,18:00 ET,UEFA,19.0,Murat Yakin,CONCACAF,30.0,Jesse Marsch
11,B,Group Stage,Bosnia and Herzegovina,Qatar,BMO Field,Toronto,Canada,2026-06-24,18:00 ET,UEFA,52.0,Sergej Barbarez,AFC,35.0,Marquez Lopez
67,L,Group Stage,Ghana,Panama,BMO Field,Toronto,Canada,2026-06-17,18:00 ET,CAF,65.0,Otto Addo,CONCACAF,53.0,Thomas Christiansen
69,L,Group Stage,Croatia,Panama,BMO Field,Toronto,Canada,2026-06-23,21:00 ET,UEFA,11.0,Zlatko Dalić,CONCACAF,53.0,Thomas Christiansen
83,NaN,Round of 32,1L,2K,BC Place,Vancouver,Canada,2026-07-03,TBD,NaN,NaN,NaN,NaN,NaN,NaN
84,NaN,Round of 32,Best 3rd #1,Best 3rd #2,BMO Field,Toronto,Canada,2026-07-03,TBD,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
## exercise 5: Find all matches played in either "Toronto" or "Vancouver"

df[(df["city"] == "Toronto") | (df["city"] == "Vancouver")]

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
6,B,Group Stage,Canada,Bosnia and Herzegovina,BMO Field,Toronto,Canada,2026-06-12,15:00 ET,CONCACAF,30.0,Jesse Marsch,UEFA,52.0,Sergej Barbarez
8,B,Group Stage,Switzerland,Bosnia and Herzegovina,BC Place,Vancouver,Canada,2026-06-18,15:00 ET,UEFA,19.0,Murat Yakin,UEFA,52.0,Sergej Barbarez
9,B,Group Stage,Canada,Qatar,BC Place,Vancouver,Canada,2026-06-19,18:00 ET,CONCACAF,30.0,Jesse Marsch,AFC,35.0,Marquez Lopez
10,B,Group Stage,Switzerland,Canada,BC Place,Vancouver,Canada,2026-06-24,18:00 ET,UEFA,19.0,Murat Yakin,CONCACAF,30.0,Jesse Marsch
11,B,Group Stage,Bosnia and Herzegovina,Qatar,BMO Field,Toronto,Canada,2026-06-24,18:00 ET,UEFA,52.0,Sergej Barbarez,AFC,35.0,Marquez Lopez
67,L,Group Stage,Ghana,Panama,BMO Field,Toronto,Canada,2026-06-17,18:00 ET,CAF,65.0,Otto Addo,CONCACAF,53.0,Thomas Christiansen
69,L,Group Stage,Croatia,Panama,BMO Field,Toronto,Canada,2026-06-23,21:00 ET,UEFA,11.0,Zlatko Dalić,CONCACAF,53.0,Thomas Christiansen
83,NaN,Round of 32,1L,2K,BC Place,Vancouver,Canada,2026-07-03,TBD,NaN,NaN,NaN,NaN,NaN,NaN
84,NaN,Round of 32,Best 3rd #1,Best 3rd #2,BMO Field,Toronto,Canada,2026-07-03,TBD,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
## exercise 5: Find all matches played in either "Toronto" or "Vancouver"

df[(df["city"] == "Toronto") | (df["city"] == "Vancouver")].shape # to know the total

(9, 15)

In [48]:
## exercise 6: Find all matches where:
# - team1 is ranked better than team2 AND
# - match either in Mexico or Canada

mask =  (
    (df["team1_fifa_rank"] < df["team2_fifa_rank"]) &
    (
        (df["country"] == "Mexico") |
        (df["country"] == "Canada")))

df[mask]

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
0,A,Group Stage,Mexico,South Africa,Estadio Azteca,Mexico City,Mexico,2026-06-11,20:00 ET,CONCACAF,15.0,Javier Aguirre,CAF,60.0,Hugo Broos
1,A,Group Stage,South Korea,Czechia,Estadio Akron,Guadalajara,Mexico,2026-06-11,22:00 ET,AFC,25.0,Hong Myung-bo,UEFA,41.0,Ivan Hasek
3,A,Group Stage,Czechia,South Africa,Estadio Akron,Guadalajara,Mexico,2026-06-18,18:00 ET,UEFA,41.0,Ivan Hasek,CAF,60.0,Hugo Broos
6,B,Group Stage,Canada,Bosnia and Herzegovina,BMO Field,Toronto,Canada,2026-06-12,15:00 ET,CONCACAF,30.0,Jesse Marsch,UEFA,52.0,Sergej Barbarez
8,B,Group Stage,Switzerland,Bosnia and Herzegovina,BC Place,Vancouver,Canada,2026-06-18,15:00 ET,UEFA,19.0,Murat Yakin,UEFA,52.0,Sergej Barbarez
9,B,Group Stage,Canada,Qatar,BC Place,Vancouver,Canada,2026-06-19,18:00 ET,CONCACAF,30.0,Jesse Marsch,AFC,35.0,Marquez Lopez
10,B,Group Stage,Switzerland,Canada,BC Place,Vancouver,Canada,2026-06-24,18:00 ET,UEFA,19.0,Murat Yakin,CONCACAF,30.0,Jesse Marsch
31,F,Group Stage,Sweden,Tunisia,Estadio BBVA,Monterrey,Mexico,2026-06-14,20:00 ET,UEFA,39.0,Jon Dahl Tomasson,CAF,40.0,Faouzi Benzarti
44,H,Group Stage,Spain,Saudi Arabia,Estadio Akron,Guadalajara,Mexico,2026-06-21,21:00 ET,UEFA,2.0,Luis de la Fuente,AFC,57.0,Roberto Mancini
69,L,Group Stage,Croatia,Panama,BMO Field,Toronto,Canada,2026-06-23,21:00 ET,UEFA,11.0,Zlatko Dalić,CONCACAF,53.0,Thomas Christiansen

In [53]:
## exercise 6: Find all matches where:
# - team1 is ranked better than team2 AND
# - match either in Mexico or Canada

df[(df["team1_fifa_rank"] < df["team2_fifa_rank"]) &
    ((df["country"] == "Mexico") | (df["country"] == "Canada"))]

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
0,A,Group Stage,Mexico,South Africa,Estadio Azteca,Mexico City,Mexico,2026-06-11,20:00 ET,CONCACAF,15.0,Javier Aguirre,CAF,60.0,Hugo Broos
1,A,Group Stage,South Korea,Czechia,Estadio Akron,Guadalajara,Mexico,2026-06-11,22:00 ET,AFC,25.0,Hong Myung-bo,UEFA,41.0,Ivan Hasek
3,A,Group Stage,Czechia,South Africa,Estadio Akron,Guadalajara,Mexico,2026-06-18,18:00 ET,UEFA,41.0,Ivan Hasek,CAF,60.0,Hugo Broos
6,B,Group Stage,Canada,Bosnia and Herzegovina,BMO Field,Toronto,Canada,2026-06-12,15:00 ET,CONCACAF,30.0,Jesse Marsch,UEFA,52.0,Sergej Barbarez
8,B,Group Stage,Switzerland,Bosnia and Herzegovina,BC Place,Vancouver,Canada,2026-06-18,15:00 ET,UEFA,19.0,Murat Yakin,UEFA,52.0,Sergej Barbarez
9,B,Group Stage,Canada,Qatar,BC Place,Vancouver,Canada,2026-06-19,18:00 ET,CONCACAF,30.0,Jesse Marsch,AFC,35.0,Marquez Lopez
10,B,Group Stage,Switzerland,Canada,BC Place,Vancouver,Canada,2026-06-24,18:00 ET,UEFA,19.0,Murat Yakin,CONCACAF,30.0,Jesse Marsch
31,F,Group Stage,Sweden,Tunisia,Estadio BBVA,Monterrey,Mexico,2026-06-14,20:00 ET,UEFA,39.0,Jon Dahl Tomasson,CAF,40.0,Faouzi Benzarti
44,H,Group Stage,Spain,Saudi Arabia,Estadio Akron,Guadalajara,Mexico,2026-06-21,21:00 ET,UEFA,2.0,Luis de la Fuente,AFC,57.0,Roberto Mancini
69,L,Group Stage,Croatia,Panama,BMO Field,Toronto,Canada,2026-06-23,21:00 ET,UEFA,11.0,Zlatko Dalić,CONCACAF,53.0,Thomas Christiansen

In [52]:
## exercise 6: Find all matches where:
# - team1 is ranked better than team2 AND
# - match either in Mexico or Canada

df[(df["team1_fifa_rank"] < df["team2_fifa_rank"]) &
    ((df["country"] == "Mexico") | (df["country"] == "Canada"))].shape

(10, 15)

In [121]:
## exercise 6: Find all matches where:
# - team1 is ranked better than team2 AND
# - match either in Mexico or Canada

# Drop all missing values
# Row with a single NaN value --- is dropped
# df.dropna(inplace = True) # Original will be affected

# df.info()

# give me an aggregate for the two columns
df[['team1_fifa_rank', 'team2_fifa_rank']].min(axis = 0)

team1_fifa_rank    1.0
team2_fifa_rank    1.0
dtype: float64

In [120]:
# give me an aggregate for the all the 72 rows
df[['team1_fifa_rank', 'team2_fifa_rank']].min(axis = 1)

0     15.0
1     25.0
2     15.0
3     41.0
4     15.0
      ...
67    53.0
68     4.0
69    11.0
70     4.0
71    11.0
Length: 72, dtype: float64

In [122]:
df['team2_fifa_rank'].agg(['mean','min','max', 'count', 'std', 'var', 'prod'])

mean      3.791667e+01
min       1.000000e+00
max       9.500000e+01
count     7.200000e+01
std       2.383674e+01
var       5.681901e+02
prod     1.317922e+104
Name: team2_fifa_rank, dtype: float64

In [ ]:
## sorting data in data frames

# - df.sort_value(by = 'colummn')
# - df.sort_index()

In [ ]:
## Aggregation

# -

In [ ]:
df = pd.read_csv("wc_2026.csv")

df.team1_fifa_rank.max()

95.0

In [80]:
df.team1_fifa_rank.min()

df[["team1_fifa_rank","team2_fifa_rank" ]].min()
df[["team1_fifa_rank","team2_fifa_rank" ]].max()
df[["team1_fifa_rank","team2_fifa_rank" ]].mean()
df[["team1_fifa_rank","team2_fifa_rank" ]].median()


# df[["team1_fifa_rank","team2_fifa_rank" ]].mode()

team1_fifa_rank    24.0
team2_fifa_rank    35.5
dtype: float64

In [78]:
df[["team1_fifa_rank","team2_fifa_rank" ]].mean(axis= 0)

team1_fifa_rank    30.208333
team2_fifa_rank    37.916667
dtype: float64

In [68]:
df[(df["team1_fifa_rank"] <5) | (df["team2_fifa_rank"] <5)]

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
42,H,Group Stage,Spain,Cape Verde,Mercedes-Benz Stadium,Atlanta,USA,2026-06-15,12:00 ET,UEFA,2.0,Luis de la Fuente,CAF,70.0,Pedro Brito
44,H,Group Stage,Spain,Saudi Arabia,Estadio Akron,Guadalajara,Mexico,2026-06-21,21:00 ET,UEFA,2.0,Luis de la Fuente,AFC,57.0,Roberto Mancini
47,H,Group Stage,Uruguay,Spain,Estadio Akron,Guadalajara,Mexico,2026-06-26,20:00 ET,CONMEBOL,17.0,Marcelo Bielsa,UEFA,2.0,Luis de la Fuente
48,I,Group Stage,France,Senegal,MetLife Stadium,East Rutherford,USA,2026-06-16,15:00 ET,UEFA,1.0,Didier Deschamps,CAF,14.0,Aliou Cissé
50,I,Group Stage,France,Iraq,Lincoln Financial Field,Philadelphia,USA,2026-06-22,17:00 ET,UEFA,1.0,Didier Deschamps,AFC,61.0,Graham Arnold
52,I,Group Stage,Norway,France,MetLife Stadium,East Rutherford,USA,2026-06-26,15:00 ET,UEFA,44.0,Ståle Solbakken,UEFA,1.0,Didier Deschamps
54,J,Group Stage,Argentina,Algeria,Arrowhead Stadium,Kansas City,USA,2026-06-16,21:00 ET,CONMEBOL,3.0,Lionel Scaloni,CAF,36.0,Vladimir Petkovic
56,J,Group Stage,Argentina,Austria,AT&T Stadium,Arlington,USA,2026-06-22,13:00 ET,CONMEBOL,3.0,Lionel Scaloni,UEFA,23.0,Ralf Rangnick
59,J,Group Stage,Jordan,Argentina,AT&T Stadium,Arlington,USA,2026-06-27,22:00 ET,AFC,68.0,Hussain Ammouta,CONMEBOL,3.0,Lionel Scaloni
66,L,Group Stage,England,Croatia,AT&T Stadium,Arlington,USA,2026-06-17,15:00 ET,UEFA,4.0,Thomas Tuchel,UEFA,11.0,Zlatko Dalić
68,L,Group Stage,England,Ghana,Gillette Stadium,Foxborough,USA,2026-06-23,19:00 ET,UEFA,4.0,Thomas Tuchel,CAF,65.0,Otto Addo
70,L,Group Stage,Panama,England,MetLife Stadium,East Rutherford,USA,2026-06-27,15:00 ET,CONCACAF,53.0,Thomas Christiansen,UEFA,4.0,Thomas Tuchel

In [82]:
df_emp = pd.read_csv("employee.csv")
df_emp

      Name   Department  Salary  Experience
0    Alice  Engineering   75000           3
1      Bob    Marketing   65000           5
2  Charlie  Engineering   80000           7
3    Diana           HR   60000           2
4      Eve    Marketing   70000           4

In [ ]:
## NUMPY

# - In NumPy (arrays), axis refers to dimensions of an array:

# - axis = 0 → column-wise (down the rows)
# - axis = 1 → row-wise (across columns)


## PANDAS

# - In Pandas, axis works similarly but is tied to rows and columns in a DataFrame:

# - axis = 0 → operate down the rows (column-wise operation)
# - axis = 1 → operate across columns (row-wise operation)


### DROP ARGUMENT:

# - df.drop(axis = 0) # drop rows / vertical
# - df.drop(axis = 1) # drop columns / horizontal

In [ ]:
df_emp[['Salary', 'Experience']].mean(axis = 0) # column-wise

Salary        70000.0
Experience        4.2
dtype: float64

In [ ]:
df_emp[['Salary', 'Experience']].mean(axis = 1) # row-wise

0    37501.5
1    32502.5
2    40003.5
3    30001.0
4    35002.0
dtype: float64

In [ ]:
df_emp.drop("Name", axis = 1) # targetting the header & its column

    Department  Salary  Experience
0  Engineering   75000           3
1    Marketing   65000           5
2  Engineering   80000           7
3           HR   60000           2
4    Marketing   70000           4

In [ ]:
df_emp.drop("Department", axis = 1) # targetting the header & its column

      Name  Salary  Experience
0    Alice   75000           3
1      Bob   65000           5
2  Charlie   80000           7
3    Diana   60000           2
4      Eve   70000           4

In [ ]:
## to drop all missing values

df.dropna()

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
0,A,Group Stage,Mexico,South Africa,Estadio Azteca,Mexico City,Mexico,2026-06-11,20:00 ET,CONCACAF,15.0,Javier Aguirre,CAF,60.0,Hugo Broos
1,A,Group Stage,South Korea,Czechia,Estadio Akron,Guadalajara,Mexico,2026-06-11,22:00 ET,AFC,25.0,Hong Myung-bo,UEFA,41.0,Ivan Hasek
2,A,Group Stage,South Korea,Mexico,Estadio Akron,Guadalajara,Mexico,2026-06-18,21:00 ET,AFC,25.0,Hong Myung-bo,CONCACAF,15.0,Javier Aguirre
3,A,Group Stage,Czechia,South Africa,Estadio Akron,Guadalajara,Mexico,2026-06-18,18:00 ET,UEFA,41.0,Ivan Hasek,CAF,60.0,Hugo Broos
4,A,Group Stage,Czechia,Mexico,Estadio Azteca,Mexico City,Mexico,2026-06-24,21:00 ET,UEFA,41.0,Ivan Hasek,CONCACAF,15.0,Javier Aguirre
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,L,Group Stage,Ghana,Panama,BMO Field,Toronto,Canada,2026-06-17,18:00 ET,CAF,65.0,Otto Addo,CONCACAF,53.0,Thomas Christiansen
68,L,Group Stage,England,Ghana,Gillette Stadium,Foxborough,USA,2026-06-23,19:00 ET,UEFA,4.0,Thomas Tuchel,CAF,65.0,Otto Addo
69,L,Group Stage,Croatia,Panama,BMO Field,Toronto,Canada,2026-06-23,21:00 ET,UEFA,11.0,Zlatko Dalić,CONCACAF,53.0,Thomas Christiansen
70,L,Group Stage,Panama,England,MetLife Stadium,East Rutherford,USA,2026-06-27,15:00 ET,CONCACAF,53.0,Thomas Christiansen,UEFA,4.0,Thomas Tuchel
71,L,Group Stage,Croatia,Ghana,MetLife Stadium,East Rutherford,USA,2026-06-27,15:00 ET,UEFA,11.0,Zlatko Dalić,CAF,65.0,Otto Addo

In [99]:
## to drop all missing values

df.dropna(inplace = True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 72 entries, 0 to 71
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   group                72 non-null     object
 1   stage                72 non-null     object
 2   team1                72 non-null     object
 3   team2                72 non-null     object
 4   venue                72 non-null     object
 5   city                 72 non-null     object
 6   country              72 non-null     object
 7   date                 72 non-null     object
 8   kickoff_et           72 non-null     object
 9   team1_confederation  72 non-null     object
 10  team1_fifa_rank      72 non-null     float64
 11  team1_coach          72 non-null     object
 12  team2_confederation  72 non-null     object
 13  team2_fifa_rank      72 non-null     float64
 14  team2_coach          72 non-null     object
dtypes: float64(2), object(13)
memory usage: 9.0+ KB

In [ ]:
# min for each column : column-wise

df[['team1_fifa_rank', 'team2_fifa_rank']].min(axis=0)

team1_fifa_rank    1.0
team2_fifa_rank    1.0
dtype: float64

In [ ]:
# min between two columns : row-wise

df[['team1_fifa_rank', 'team2_fifa_rank']].min(axis=1)

0     15.0
1     25.0
2     15.0
3     41.0
4     15.0
      ...
67    53.0
68     4.0
69    11.0
70     4.0
71    11.0
Length: 72, dtype: float64

In [ ]:
## aggregates

In [ ]:
### GROUPING

# - group the data by some category
# - using df.groupby('category').count() : will give the full columns / dataset
# using df.groupby('category').size() : will only give the total counts for respective category

In [105]:
df_emp.head()

      Name   Department  Salary  Experience
0    Alice  Engineering   75000           3
1      Bob    Marketing   65000           5
2  Charlie  Engineering   80000           7
3    Diana           HR   60000           2
4      Eve    Marketing   70000           4

In [111]:
df_emp.groupby("Department")[["Name", "Salary", "Experience"]].count()

             Name  Salary  Experience
Department
Engineering     2       2           2
HR              1       1           1
Marketing       2       2           2

In [114]:
df_emp.groupby("Department")[["Name", "Salary", "Experience"]].min()

              Name  Salary  Experience
Department
Engineering  Alice   75000           3
HR           Diana   60000           2
Marketing      Bob   65000           4

In [ ]:
df.groupby("country").count() # using df.groupby('category').count() : will give the full columns / dataset

,group,stage,team1,team2,venue,city,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
country,,,,,,,,,,,,,,
Canada,7,7,7,7,7,7,7,7,7,7,7,7,7,7
Mexico,12,12,12,12,12,12,12,12,12,12,12,12,12,12
USA,53,53,53,53,53,53,53,53,53,53,53,53,53,53

In [ ]:
df.groupby("country").size() # using df.groupby('category').size() : will only give the total counts for respective category

country
Canada     7
Mexico    12
USA       53
dtype: int64

In [ ]:
### COMBINING DATAFRAMES

# JOINS : used to combine two tables

In [118]:
df_student = pd.read_csv("student_marks.csv")

In [ ]:
### MATPLOTLIB