### PANDAS
- python library
- fast, powerful, flexible & easy to use open source data **analysis** & ""manipulation** tool
- provides Series & Dataframe objects
- these objects used to store & manipulate structured data (data in tabular form)
- pandas comes from Panel Data
- pythn for Data Analysis
- s refers to series of object

In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\user\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\user\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd

In [ ]:
## Core Objects:
# - Series
# - Dataframe :

In [ ]:
# eg series

maths = pd.Series([20,30,40], dtype = 'int8', name = 'math')
type(maths)

print(maths)

0    20
1    30
2    40
Name: math, dtype: int8

In [ ]:
english = pd.Series([20,30,40])
python = pd.Series([20,30,40])
science = pd.Series([20,30,40])

In [16]:
# Dataframe

df = pd.concat([maths, english, python, science], axis = 1)
df

   math   0   1   2
0    20  20  20  20
1    30  30  30  30
2    40  40  40  40

In [ ]:
# Dataframe

df = pd.concat([maths, english, python, science], axis = 1)

type(df)

pandas.core.frame.DataFrame

In [35]:
# Dataframe from dictionary of lists --- 

data = {
    "students" : ["Nomie", "Idrees", "Radia"],
    "Maths" : [85,95,90],
    "English" : [75, 85, 80],
}

df = pd.DataFrame(data)
print(df)
display(df)

  students  Maths  English
0    Nomie     85       75
1   Idrees     95       85
2    Radia     90       80

  students  Maths  English
0    Nomie     85       75
1   Idrees     95       85
2    Radia     90       80

In [41]:
# Dataframe from dictionary of lists --- 

data = {
    "students" : ["Nomie", "Idrees", "Radia"],
    "Maths" : [85,95,90],
    "English" : [75, 85, 80],
}

df = pd.DataFrame(data)
print(df)
display(df)

print(df.iloc[-2:,[0,2]])

  students  Maths  English
0    Nomie     85       75
1   Idrees     95       85
2    Radia     90       80

  students  Maths  English
0    Nomie     85       75
1   Idrees     95       85
2    Radia     90       80

  students  English
1   Idrees       85
2    Radia       80

In [ ]:
# DataFrame from List of Dictionaries --- 

data = [
    {'Name': 'Alice', 'Age': 25, 'City': 'New York'},
    {'Name': 'Bob', 'Age': 30, 'City': 'London'},
    {'Name': 'Charlie', 'Age': 35, 'City': 'Paris'}
]
 
df = pd.DataFrame(data)
df
# print(df)

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris

In [29]:

temp = pd.Series([30, 35, 37, 31, 33],  dtype = 'int8', name = 'Temperature')
type(temp)

print(temp)

0    30
1    35
2    37
3    31
4    33
Name: Temperature, dtype: int8

In [23]:
data = {
    "City" : ["KL", "Sepang", "Nilai"],
    "Temperature" : [37,38.5,39],
}

df = pd.DataFrame(data)
print(df)
display(df)
type(df)

     City  Temperature
0      KL         37.0
1  Sepang         38.5
2   Nilai         39.0

     City  Temperature
0      KL         37.0
1  Sepang         38.5
2   Nilai         39.0

pandas.core.frame.DataFrame

In [21]:
data = {
    "City" : ["KL", "Sepang", "Nilai"],
    "Temperature" : [37,38.5,39],
}

df = pd.DataFrame(data)
type(df)

pandas.core.frame.DataFrame

In [30]:
# Let's create a sample CSV file first, then read it
sample_data = """Name,Department,Salary,Experience
Alice,Engineering,75000,3
Bob,Marketing,65000,5
Charlie,Engineering,80000,7
Diana,HR,60000,2
Eve,Marketing,70000,4"""

with open("employee.csv", "w") as f:
    f.write(sample_data)

In [31]:
df = pd.read_csv("employee.csv")

In [ ]:
df.iloc[]